### PR TITLE
📝 Update cert-manager-issuers's readme to have clusterIssues (plural) like values

### PR DESCRIPTION
**Pull request by halkeye**
README has clusterIssuer, but templates are clusterIssuers

### What is the new behavior?

-
-
-

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting or renaming that would not cause existing functionality to change)
- [ ] Refactoring (no functional changes and no API changes)
- [ ] Build-related changes (improve Github Action workflows)
- [ ] Documentation content changes (add or improve existing documentation)
- [ ] Other (please describe):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by xunleii** [comment]
Hi @halkeye, sorry for this wait and thanks for your issue.
I will try to fix the doc the weekend or the next one

**Comment by xunleii** [comment]
Hi @halkeye, sorry for this long wait.
LGTM but can you use the https://gitmoji.dev/ format for your commit ? I have a plan to add a Changelog generator based on this format _(in the future... maybe)_

**Comment by halkeye** [comment]
I can try and remember to do it tomorrow, but as it's just updating the docs example I'm not sure it needs a changelog or release

**Comment by xunleii** [comment]
Hi @halkeye, I know and sorry to bother you with that, it just to keep all commits consistent together

**Comment by halkeye** [comment]
does that work?

**Comment by xunleii** [comment]
> does that work?

Yes, perfect. Thanks a lot !

**Review by xunleii — APPROVED** [review]

**Pull request merged**
