### PR TITLE
:ambulance: (apps/jellyfin): add `fsgroup` to `podSecurityPolicy`

### PR DESCRIPTION
**Pull request by psych0d0g**
## Description

to make sure to be able to actually write into PVC provided storage, add an fsGroup parameter to the default values.yaml so the the mounted storage is not owned by root:root when a security policy is active

### What is the current behavior?
when we deploy jellyfin using mostly defaults from values.yaml, and add PVC storage to it it crashloops with an access denied error on the path /opt/jellyfin/data/data. the mount is owned by the user root and group root with no permissions that allow non-root writes

### What is the new behavior?
the mounted PVCs are owned by root:jellyfin, writes are now possible

### CODE REVIEW

**Comment by xunleii** [comment]
Hi @psych0d0g, thanks for this fix !

However, this PR requires some minor changes :
- Can you update the Ubuntu version on the [Jellyfin dockerfile](https://github.com/beluga-cloud/charts/blob/main/charts/jellyfin/images/jellyfin/Dockerfile#L1) to `ubuntu:jellyfish` ? This should fix the CI
- Can you update the Chart version ? (minor or patch, as you want)
- Finally, can you run `just build-external` into `charts/jellyfin` directory to update assets like the README.md ?

---
To be honest, I don't recommend using these Charts at the moment; with the exception of the Actual Budget chart, the other charts aren't very well maintained and won't be for a few months.

I'm going to update the README for this project to add this point and avoid any inconvenience for people using these Charts.

**Comment by psych0d0g** [comment]
requested changes where implemented :)
ill keep using the jellyfin chart tho, i like the way it it build the most and would probably create mr's if i hit any roadblocks in the future.
i am also thinking about creating a qbittorrent chart following the style from you jellyfin chart.

**Review by xunleii — CHANGES_REQUESTED** [review]
I'm sorry to bother you with this, but can you rename the commits using the [gitmoji](https://gitmoji.dev) format?
I was planning to generate a complete CHANGELOG per charts based on this format (which is very complete).

If it can helps you, here is a suggestion of commit values
```
:ambulance: (apps/jellyfin): add `fsgroup` to podSecurityPolicy
:arrow_up: (deps): bump docker base image to `ubuntu:jellyfish`
:arrow_up: (deps): bump chart version
:package: (apps/jellyfin): update and rebuild all packaging files
```

_NOTE: the CI is probably broken on the README checks, so don't take care of it. I will force merge even if it fails_

**Comment by xunleii** [comment]
> requested changes where implemented :) ill keep using the jellyfin chart tho, i like the way it is build the most compared to several others and would probably create pr's if i hit any roadblocks in the future. i am also thinking about creating a qbittorrent chart following the style from your jellyfin chart.

Thanks a lot for your contribution. If it can help you, there is a command `just` called `bootstrap` to interactively create a new app _(if it's not broken)_.

**Pull request merged**
